export const categories = Object.freeze({
  api: 'API',
  app: 'Apps, Plataformas e Softwares',
  database: 'Banco de Dados',
  ci: 'CI/CD',
  devops: 'DevOps',
  language: 'Linguagens de Programação',
  performance: 'Performance',
  test: 'Testes',
  theme: 'Temas',
  plugin: 'Plug-ins',
  cli: 'CLI',
  educational: 'Educacionais',
  career: 'Carreira',
  tool: 'Ferramentas',
  frontend: 'Frontend',
  backend: 'Backend',
  observability: 'Observabilidade',
  machinelearning: 'Machine Learning',
  ai: 'Inteligência Artificial',
  ui: 'UI/UX',
  frameworks: 'Livrarias e Frameworks',
  security: 'Segurança e Privacidade',
  productivity: 'Produtividade',
  list: 'Listas',
});
