export const languages = Object.freeze({
  c: 'C',
  csharp: 'C#',
  cpp: 'C++',
  css: 'CSS',
  clojure: 'Clojure',
  dart: 'Dart',
  delphi: 'Delphi',
  haskell: 'Haskell',
  javascript: 'JavaScript',
  typescript: 'TypeScript',
  php: 'PHP',
  shell: 'Shell',
  go: 'GO',
  lua: 'Lua',
  ruby: 'Ruby',
  elixir: 'Elixir',
  rust: 'Rust',
  java: 'Java',
  swift: 'Swift',
  vim: 'Vim Script',
  python: 'Python',
  zig: 'Zig',
});
