/*---------------------------------------------------------------------------------------------
 *  Copyright (c) https://awesomeyou.io and contributors. All rights reserved.
 *  Licensed under the GNU Affero General Public License v3.0. See https://github.com/wellwelwel/awesomeyou/blob/main/LICENSE for license information.
 *--------------------------------------------------------------------------------------------*/

import { readFile } from 'node:fs/promises';
import { listFiles, strict, test } from 'poku';

test('Ensure License references', async () => {
  const headers = [
    '// Generated by Docusaurus',
    '// Generated by Wrangler',
    '// Generated by Rollup',
    '/*--------------------------------------------------------------------------------------------- *  Copyright (c) https://awesomeyou.io and contributors. All rights reserved. *  Licensed under the GNU Affero General Public License v3.0. See https://github.com/wellwelwel/awesomeyou/blob/main/LICENSE for license information. *--------------------------------------------------------------------------------------------*/',
  ] as const;

  const files = await listFiles('./', {
    filter: /\.(js|ts|tsx|mjs|mts|scss)$/,
    exclude: [/\.wrangler\//, /\.docusaurus/, /build\//, /server\//],
  });

  for (const file of files) {
    const content = (await readFile(file, 'utf8')).replace(/\n/g, '').trim();

    strict(
      content.startsWith(headers[0]) ||
        content.startsWith(headers[1]) ||
        content.startsWith(headers[2]) ||
        content.startsWith(headers[3]),
      `Ensure License reference for ${file}`
    );
  }
});
